services:
    rmcgirr83.topicdescription.listener:
        class: rmcgirr83\topicdescription\event\listener
        arguments:
            - '@auth'
            - '@request'
            - '@template'
            - '@language'
        tags:
            - { name: event.listener }
